Update to allow automated mode and split of server, clinet and server_client certificates

diff --git a/create-root-ca b/create-root-ca
--- a/create-root-ca
+++ b/create-root-ca
@@ -2,20 +2,23 @@
 # Derek Moore <derek.moore@gmail.com>
 
 usage() {
-    echo "Usage: $0 -d CA_DIR"
+    echo "Usage: $0 -d CA_DIR [-A]"
     echo "Initializes a new root CA in CA_DIR"
     echo
     echo "Options:"
     echo "    -d CA_DIR  Target directory to be created and initialized"
+    echo "    -A         Automateion mode, password read from env_variable EASY_CA_PASS"
     echo
     exit 2
 }
 
 CA_DIR=
+AUTOMODE=false
 
-while getopts d: FLAG; do
+while getopts Ad: FLAG; do
     case $FLAG in
         d) CA_DIR=${OPTARG} ;;
+        A) AUTOMODE=true ;;
         *) usage ;;
     esac
 done
@@ -30,6 +33,7 @@ source ${BIN_DIR}/functions
 
 HOME=$CA_DIR
 CA_NAME=$( basename "${HOME}" )
+export SAN=""
 
 echo
 echo "Creating root CA in '${HOME}'"
@@ -39,19 +43,28 @@ init_ca_home ${HOME}
 generate_conf ${HOME}/bin/defaults.conf
 source ${HOME}/bin/defaults.conf
 
-echo
-echo -n "Enter passphase for encrypting root CA key: "
-read -s PASS1
-echo
-echo -n "Verifying - Enter passphase for encrypting root CA key: "
-read -s PASS2
-echo
-
-if [ "${PASS1}" != "${PASS2}" ]; then
-    echo "Passphrases did not match, exiting."
-    exit 1
+# Get the password
+if [ "${AUTOMODE}" = true ] ; then
+    if [ -z "${EASY_CA_PASS}" ] ; then
+        echo "ERROR: Automode set but no (or empty) password provided"
+        exit 1
+    else
+        export CA_PASS=${EASY_CA_PASS}
+    fi
+else
+    echo
+    echo -n "Enter passphase for encrypting root CA key: "
+    read -s PASS1
+    echo
+    echo -n "Verifying - Enter passphase for encrypting root CA key: "
+    read -s PASS2
+    echo
+    if [ "${PASS1}" != "${PASS2}" ]; then
+        echo "ERROR: Passphrases did not match, exiting."
+        exit 1
+    fi
+    export CA_PASS=${PASS1}
 fi
-export CA_PASS=${PASS1}
 
 pushd ${HOME} > /dev/null
 
@@ -59,7 +72,7 @@ pushd ${HOME} > /dev/null
 template "${BIN_DIR}/templates/root.tpl" "conf/ca.conf"
 
 # Create the root CA csr
-openssl genrsa -out ca/private/ca.key -passout env:CA_PASS 4096
+openssl genrsa -out ca/private/ca.key -passout env:CA_PASS 8192
 chmod 0400 ca/private/ca.key
 
 # Create the root CA csr
@@ -74,7 +87,7 @@ openssl ca -selfsign -batch -notext \
            -config conf/ca.conf \
            -in ca/ca.csr \
            -out ca/ca.crt \
-           -days 3652 \
+           -days 7300 \
            -extensions root_ca_ext \
            -passin env:CA_PASS
 
diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -7,6 +7,8 @@ create-root-ca
 create-signing-ca
 create-server
 create-client
+create-server-client
+create-one_liner
 revoke-cert
 functions
 "
@@ -51,13 +53,13 @@ init_ca_home() {
 
     # Ensure we're initializing an empty directory
     if [ -d "${HOME}" ]; then
-	echo "${HOME} already exists, exiting"
-	exit 1
+    echo "ERROR: ${HOME} already exists, exiting"
+    exit 1
     fi
 
     if ! mkdir -p "${HOME}"; then
-        echo "Unable to create ${HOME}, exiting"
-	exit 1
+        echo "ERROR: Unable to create ${HOME}, exiting"
+        exit 1
     fi
 
     pushd ${HOME} > /dev/null
@@ -74,6 +76,7 @@ init_ca_home() {
     mkdir -p conf
     mkdir -p csr
     mkdir -p private
+    mkdir -p one_liner
 
     # Secure key directories
     chmod 0700 ca/private
@@ -97,18 +100,26 @@ generate_conf() {
     DEST=$1
 
     echo -n "Short label for new CA [${CA_NAME}]: "
-    read NAME
+    if [ "${AUTOMODE}" = false ] ; then
+        read NAME
+    else
+        echo "${CA_NAME}"
+    fi
     if [ -n "${NAME}" ]; then
         CA_NAME=${NAME}
         CA_NAME=`echo ${CA_NAME} | sed 's/[^A-Za-z0-9-]/-/g'`
     fi
 
     echo -n "Domain name for new CA [${CA_DOMAIN}]: "
-    read DOMAIN
+    if [ "${AUTOMODE}" = false ] ; then
+        read DOMAIN
+    else
+        echo "${CA_DOMAIN}"
+    fi
     if [ -n "${DOMAIN}" ]; then
         CA_DOMAIN=${DOMAIN}
     elif [ -z "${CA_DOMAIN}" ]; then
-        echo "Domain is required."
+        echo "ERROR: Domain is required."
         exit 1
     fi
 
@@ -117,31 +128,51 @@ generate_conf() {
     echo
 
     echo -n "Default country code for new certificates [${CA_CERT_C}]: "
-    read CERT_C
+    if [ "${AUTOMODE}" = false ] ; then
+        read CERT_C
+    else
+        echo "${CA_CERT_C}"
+    fi
     if [ -n "${CERT_C}" ]; then
         CA_CERT_C=${CERT_C}
     fi
 
     echo -n "Default state for new certificates [${CA_CERT_ST}]: "
-    read CERT_ST
+    if [ "${AUTOMODE}" = false ] ; then
+        read CERT_ST
+    else
+        echo "${CA_CERT_ST}"
+    fi
     if [ -n "${CERT_ST}" ]; then
         CA_CERT_ST=${CERT_ST}
     fi
 
     echo -n "Default city for new certificates [${CA_CERT_L}]: "
-    read CERT_L
+    if [ "${AUTOMODE}" = false ] ; then
+        read CERT_L
+    else
+        echo "${CA_CERT_L}"
+    fi
     if [ -n "${CERT_L}" ]; then
         CA_CERT_L=${CERT_L}
     fi
 
     echo -n "Default org for new certificates [${CA_CERT_O}]: "
-    read CERT_O
+    if [ "${AUTOMODE}" = false ] ; then
+        read CERT_O
+    else
+        echo "${CA_CERT_O}"
+    fi
     if [ -n "${CERT_O}" ]; then
         CA_CERT_O=${CERT_O}
     fi
 
     echo -n "Default org unit for new certificates [${CA_CERT_OU}]: "
-    read CERT_OU
+    if [ "${AUTOMODE}" = false ] ; then
+        read CERT_OU
+    else
+        echo "${CA_CERT_OU}"
+    fi
     if [ -n "${CERT_OU}" ]; then
         CA_CERT_OU=${CERT_OU}
     fi
@@ -150,7 +181,11 @@ generate_conf() {
 
     CA_CERT_CN="${CA_CERT_O} Certificate Authority"
     echo -n "Common Name for CA certificate [${CA_CERT_CN}]: "
-    read CERT_CN
+    if [ "${AUTOMODE}" = false ] ; then
+        read CERT_CN
+    else
+        echo "${CA_CERT_CN}"
+    fi
     if [ -n "${CERT_CN}" ]; then
         CA_CERT_CN=${CERT_CN}
     fi
